CREATE TABLE authorities
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority VARCHAR(255),
    CONSTRAINT pk_authorities PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username     VARCHAR(255),
    password     VARCHAR(255),
    enabled      BOOLEAN                                 NOT NULL,
    authority_id BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT UniqueName UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_AUTHORITY FOREIGN KEY (authority_id) REFERENCES authorities (id);

CREATE TABLE posts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

INSERT INTO posts (name, description, created_at)
VALUES ('О чем этот форум?', 'Place the chickpeas in a saucepan, and varnish regularly rich with whole ice water.', NOW());

INSERT INTO posts (name, description, created_at)
VALUES ('Правила форума.', 'Combine apple, chicory and spinach. jumble with diced basil and serve warmed with tofu. Enjoy!', NOW());

INSERT INTO authorities (authority)
VALUES ('ROLE_USER');

INSERT INTO authorities (authority)
VALUES ('ROLE_ADMIN');

insert into users (username, password, enabled, authority_id)
values ('root', '$2a$10$wY1twJhMQjGVxv4y5dBC5ucCBlzkzT4FIGa4FNB/pS9GaXC2wm9/W', true,
(select id from authorities where authority = 'ROLE_ADMIN'));
