CREATE TABLE posts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

INSERT INTO posts (name, description, createdAt)
VALUES ('О чем этот форум?', 'Place the chickpeas in a saucepan, and varnish regularly rich with whole ice water.', NOW());

INSERT INTO posts (name, description, createdAt)
VALUES ('Правила форума.', 'Combine apple, chicory and spinach. jumble with diced basil and serve warmed with tofu. Enjoy!', NOW());